name: CD-RELEASE

on:
  push:
    branches: [ "release" ]

  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
    
      - name: Configure SSH AZURE
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/azure-cloud.key
          chmod 600 ~/.ssh/azure-cloud.key
          cat >>~/.ssh/config <<END
          Host azure-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/azure-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AZURE_SSH_USER }}
          SSH_KEY: ${{ secrets.AZURE_SSH_KEY }}
          SSH_HOST: ${{ secrets.AZURE_SSH_HOST }}
    
      - name: Checkout repository
        uses: actions/checkout@v3
      

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
          
      - name: Install dependencies
        run: npm install
        
        
      - name: Run the tests
        run: npm run test -- --coverage
        env:
          CI: true
        
      #- name: SonarCloud Scan
        #uses: SonarSource/sonarcloud-github-action@master
        #env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Build the application
        run: npm run build
          
      - name: Deploy de application
        run: |
          ssh azure-cloud "sudo systemctl stop sandbox-app"
          ssh azure-cloud "sudo rm -rf /sandbox/react-app"
          scp -r build azure-cloud:/home/github/react-app
          ssh azure-cloud "sudo mv /home/github/react-app /sandbox/react-app"
          ssh azure-cloud "sudo systemctl start sandbox-app"
